---
version: "2.1"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - /home/time/docker/sonarr:/config
    ports:
      - 8080:8080
    restart: unless-stopped