---
version: "2.1"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - /home/time/homer/assets:/www/assets
    ports:
      - 80:80
    restart: unless-stopped