---
title: "Home"
subtitle: "T I M E"
logo: "logo.png"

header: false
footer: '<p>Theme made with <span class="has-text-danger">❤️</span> by <a href="https://github.com/WalkxCode">Walkx</a></p>' # Set false if you want to hide it.

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "// Server"
    icon: "fas fa-cloud"
    items:
      - name: "Main Server"
        logo: "assets/tools/server.png" # Change github.png to the name of your own custom icon!
        subtitle: "Main TrueNAS Scale server!"
        tag: "server"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://server.lia"
        target: "_blank"

      - name: "Lab Server"
        logo: "assets/tools/server.png" # Change github.png to the name of your own custom icon!
        subtitle: "Second TrueNAS Scale server for testing!"
        tag: "server"
        tagstyle: "is-primary" # This will display the is-primary color! Try changing it to; is-link, is-info, is-success, is-warning or is-danger!
        url: "http://lab.lia"
        target: "_blank"

  - name: "// Services"
    icon: "fas fa-cloud"
    items:
      - name: "Plex"
        logo: "assets/tools/plex.jpg"
        subtitle: "Local video streaming!"
        tag: "video"
        tagstyle: "is-info"
        url: "http://server.lia:32400"
        target: "_blank"

      - name: "Pihole"
        logo: "assets/tools/pihole.svg"
        subtitle: "Pihole DNS!"
        tag: "DNS"
        tagstyle: "is-info"
        url: "http://192.168.10.15/admin"
        target: "_blank"

  - name: "// Hardware"
    icon: "fas fa-cloud"
    items:
      - name: "Ubiquiti UDM-Pro"
        logo: "assets/tools/ubiquiti.jpg"
        subtitle: "UniFi OS web UI!"
        tag: "coomer-hub"
        tagstyle: "is-link"
        url: "https://192.168.10.1/"
        target: "_blank"